---
# This playbook installs Apache Maven

- file:
    path: /hadoop/maven
    state: directory
    mode: 0755

- name: Install protobuf bindings
  yum: name=protobuf-c.x86_64 state=present
  tags: maven

- unarchive:
    src: http://apache.mirrors.pair.com/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
    dest: /hadoop/maven
    remote_src: True
    extra_opts: "--strip-components=1"
    #creates: /hadoop/maven/LICENSE.txt

